from pydantic import AnyHttpUrl

QUESTIONS = {
    1: "Pojęcie algorytmu; typy, własności i przykłady algorytmów.",
    2: "Diagramy i ich rola w języku SysML; różnice w językach SysML i UML.",
    3: "Modele w przestrzeni stanów. Ocena jakości i porównanie modeli.",
    4: "Metody modelowania systemów dyskretnych.",
    5: "Statystyczna analiza wyników symulacji.",
    6: "Pojęcie fuzji danych oraz główne obszary jej wykorzystania.",
    7: "Metody estymacji parametrów systemów dynamicznych Estymacja zmiennych stanu. Liniowy i rozszerzony filtr Kalmana.",
    8: "Metody identyfikacji obiektów statycznych w warunkach probabilistycznych. Identyfikacja parametryczna i nieparametryczna.",
    9: "Analityczne metody optymalizacji z ograniczeniami. Numeryczne metody optymalizacji bez i z ograniczeniami.",
    10: "Zastosowania programowania liniowego.",
    11: "Systemy podejmowania i wspomagania decyzji ? definicje, metody i algorytmy wyznaczania decyzji, zastosowania.",
    12: "Reprezentacje wiedzy i wnioskowanie w warunkach niepewności.",
    13: "Algorytmy sztucznej inteligencji.",
    14: "Hierarchiczna struktura i informatyczne narzędzia systemów informatyki przemysłowej.",
    15: "Sieci usług, sieci sensorowe, systemy Internetu rzeczy ? analiza wydajności, zarządzanie, bezpieczeństwo i zastosowania.",
    16: "Modele cyklu życia oprogramowania. Metody zbierania wymagań w projektowaniu systemów informatycznych.",
    17: "Style interakcji człowiek-komputer. Continuum Miligrama (Środowisko Realne - Środowisko Wirtualne). Cechy wirtualnej rzeczywistości (VR).",
    18: "Typy testów oprogramowania. Definicja i metody badania użyteczności.",
    19: "Specyfika przetwarzania operacyjnego (OLTP) oraz strategicznego (OLAP), proces eksploracji oraz prezentacji danych w systemach Business Intelligence.",
    20: "Proces i architektura hurtowni danych, wielowymiarowy model danych.",
    21: "Zagrożenia i zarządzanie ryzykiem w procesie ochrony infrastruktury krytycznej oraz metody ochrony infrastruktury krytycznej.",
    22: "Cykl życia przedsiębiorstwa.",
    23: "Cele i funkcje zarządzania.",
    24: "Struktura organizacyjna - uwarunkowania i kierunki ewolucji.",
    25: "Analiza popytu i podaży; rodzaje działalności gospodarczej; koszty w przedsiębiorstwie.",
    26: "Prawne i podatkowe aspekty prowadzenia działalności gospodarczej.",
    27: "Inicjowanie i definiowanie projektów. Ocena wykonalności projektów. Analiza ryzyka projektów. Określanie struktury projektów.",
    28: "Planowanie przebiegu i zasobów projektu. Budżetowanie projektu. Sterowanie przebiegiem projektu. Organizacja zespołu projektowego.",
    29: "Metody maszynowego uczenia się.",
    30: "Systemy wizyjne, metody przetwarzania obrazów.",
    31: "Złożoność obliczeniowa. Algorytmy dokładne, aproksymacyjne i heurystyczne.",
    32: "Niestacjonarność w strumieniach danych. Algorytmy detekcji zmian w strumieniach danych.",
    33: "Koncepcja i zastosowania próbkowania oszczędnego.",
    34: "Metody fuzji i asymilacji danych.",
    35: "Modelowanie i analiza sieci złożonych.",
    36: "Systemy autonomiczne. Problemy alokacji i sterowania w systemach wielorobotowych. Podejście scentralizowane i rozproszone.",
    37: "Systemy wieloagentowe. Architektura agenta. Komunikacja, koordynacja, kooperacja i konkurencja.",
    38: "Obliczenia miękkie, systemy niepewne.",
    39: "Modele chmur i mgieł obliczeniowych. Rozwiązania hybrydowe.",
    40: "Nowoczesne systemy kryptograficzne stosowane w rozproszonych systemach transakcyjnych.",
    41: "Systemy rozproszone i wirtualne.",
    42: "Definicje i własności grafów. Modele grafowe.",
}


def get_question_url(question_id: int) -> AnyHttpUrl:
    return f"https://michalskibinski109.github.io/obrona/{question_id}.html"
